name: ğŸ“– Spill the Book Tea â˜•ï¸
labels: [suggestion]
description: Got a book that shook your world? Got Characters that have have stuck with you ( eyes rolling ) ? Got Blogs that have enlightened you ? Drop them here ! ğŸ¤œğŸ¤›
body:
  - type: input
    id: book-title
    attributes:
      label: Book Title
      placeholder: Hit me with that title! ğŸ“š
    validations:
      required: true

  - type: input
    id: book-source
    attributes:
      label: Spill the Source
      placeholder: Wattpad ğŸ˜ ? Medium ğŸ¥¸? An old dusty book from Grandmaâ€™s attic? ğŸ‘»
    validations:
      required: true

  - type: textarea
    id: book-stickiness
    attributes:
      label: Stuck to Your Soul
      placeholder: What made this book impossible to forget? Give us the deets! ğŸŒš
    validations:
      required: true